import image from '../public/tennis.jpeg';

export const data = {
  compList: [
    {
      id: '대회 아이디',
      name: '챔피언스리그',
      image: image,
      date: '2024.04.10 14:00',
      location: '열우물 테니스장',
      category: '남자 복식',
      tier: {
        id: '부 아이디',
        name: '개나리부',
      },
      status: '진행 중',
      waiting: false,
    },
    {
      id: '대회 아이디',
      name: '챔피언스리그',
      image: image,
      date: '2024.04.10 14:00',
      location: '열우물 테니스장',
      category: '남자 복식',
      tier: {
        id: '부 아이디',
        name: '개나리부',
      },
      status: '진행 중',
      waiting: false,
    },
  ],

  myComp: [
    {
      id: '대회 아이디',
      name: '챔피언스리그',
      image: image,
      date: '2024.04.10 14:00',
      location: '열우물 테니스장',
      category: '남자 복식',
      tier: { name: '개나리부' },
      status: '진행 중',
      nextMatch: {
        id: null,
        teammate: [
          { id: '유저아이디', name: '자신' },
          { id: '유저아이디', name: '파트너' },
        ],
        opponent: [
          { id: '유저 아이디', name: '콩쥐' },
          { id: '유저 아이디', name: '팥쥐' },
        ],
        court: '1',
        round: 4,
      },
    },
    {
      id: '대회 아이디',
      name: '2024 초보 대회',
      image: image,
      date: '2024.04.10 14:00',
      location: '열우물 테니스장',
      category: '남자 복식',
      tier: { name: '국화부' },
      status: '진행 전',
      nextMatch: {
        id: '매치 아이디',
        teammate: [
          { id: '유저아이디', name: '자신' },
          { id: '유저아이디', name: '파트너' },
        ],
        opponent: [
          { id: '유저 아이디', name: '콩쥐' },
          { id: '유저 아이디', name: '팥쥐' },
        ],
        court: '1',
        round: 4,
      },
    },
    {
      id: '대회 아이디',
      name: '2024 초보 대회',
      image: image,
      date: '2024.04.10 14:00',
      location: '열우물 테니스장',
      category: '남자 복식',
      tier: { name: '국화부' },
      status: '종료',
      nextMatch: {
        id: '매치 아이디',
        teammate: [
          { id: '유저아이디', name: '자신' },
          { id: '유저아이디', name: '파트너' },
        ],
        opponent: [
          { id: '유저 아이디', name: '콩쥐' },
          { id: '유저 아이디', name: '팥쥐' },
        ],
        court: '1',
        round: 4,
      },
    },
    {
      id: '대회 아이디',
      name: '2024 초보 대회',
      image: image,
      date: '2024.04.10 14:00',
      location: '열우물 테니스장',
      category: '남자 복식',
      tier: { name: '국화부' },
      status: '진행 전',
      nextMatch: {
        id: '매치 아이디',
        teammate: [
          { id: '유저아이디', name: '자신' },
          { id: '유저아이디', name: '파트너' },
        ],
        opponent: null,
        court: '1',
        round: 4,
      },
    },
    {
      id: '대회 아이디',
      name: '2024 초보 대회',
      image: image,
      date: '2024.04.10 14:00',
      location: '열우물 테니스장',
      category: '남자 복식',
      tier: { name: '국화부' },
      status: '진행 전',
      nextMatch: {
        id: '매치 아이디',
        teammate: [
          { id: '유저아이디', name: '자신' },
          { id: '유저아이디', name: '파트너' },
        ],
        opponent: null,
        court: null,
        round: 4,
      },
    },
    {
      id: '대회 아이디',
      name: '2024 초보 대회',
      image: image,
      date: '2024.04.10 14:00',
      location: '열우물 테니스장',
      category: '남자 복식',
      tier: { name: '국화부' },
      status: '진행 중',
      nextMatch: {
        id: '매치 아이디',
        teammate: [
          { id: '유저아이디', name: '자신' },
          { id: '유저아이디', name: '파트너' },
        ],
        opponent: null,
        court: null,
        round: 4,
      },
    },
  ],
};
